const List<String> kRestaurantImageUrls = [
  'https://source.unsplash.com/featured/?restaurant',
  'https://source.unsplash.com/featured/?food',
  'https://source.unsplash.com/featured/?dining',
  'https://source.unsplash.com/featured/?cuisine',
  'https://source.unsplash.com/featured/?gastronomy',
  'https://source.unsplash.com/featured/?meal',
  'https://source.unsplash.com/featured/?chef',
  'https://source.unsplash.com/featured/?culinary',
  'https://source.unsplash.com/featured/?gourmet',
  'https://source.unsplash.com/featured/?delicious',
  'https://source.unsplash.com/featured/?tasty',
  'https://source.unsplash.com/featured/?yummy',
  'https://source.unsplash.com/featured/?appetizing',
  'https://source.unsplash.com/featured/?mouthwatering',
  'https://source.unsplash.com/featured/?savor',
  'https://source.unsplash.com/featured/?flavorful',
  'https://source.unsplash.com/featured/?savory',
  'https://source.unsplash.com/featured/?delectable',
  'https://source.unsplash.com/featured/?palatable',
  'https://source.unsplash.com/featured/?scrumptious',
  'https://source.unsplash.com/featured/?tasteful',
  'https://source.unsplash.com/featured/?tempting',
  'https://source.unsplash.com/featured/?delightful',
  'https://source.unsplash.com/featured/?gastronomic',
  'https://source.unsplash.com/featured/?gastro',
  'https://source.unsplash.com/featured/?feast',
  'https://source.unsplash.com/featured/?cook',
  'https://source.unsplash.com/featured/?serve',
  'https://source.unsplash.com/featured/?plate',
  'https://source.unsplash.com/featured/?dish',
  'https://source.unsplash.com/featured/?cuisine',
  'https://source.unsplash.com/featured/?dine',
  'https://source.unsplash.com/featured/?banquet',
  'https://source.unsplash.com/featured/?menu',
  'https://source.unsplash.com/featured/?kitchen',
  'https://source.unsplash.com/featured/?eat',
  'https://source.unsplash.com/featured/?refreshment',
  'https://source.unsplash.com/featured/?nutrition',
  'https://source.unsplash.com/featured/?gourmand',
  'https://source.unsplash.com/featured/?foodie',
  'https://source.unsplash.com/featured/?delicacy',
  'https://source.unsplash.com/featured/?toothsome',
  'https://source.unsplash.com/featured/?catering',
  'https://source.unsplash.com/featured/?dishes',
  'https://source.unsplash.com/featured/?bistro',
  'https://source.unsplash.com/featured/?restaurantinterior',
  'https://source.unsplash.com/featured/?restaurantexterior',
  'https://source.unsplash.com/featured/?chefcooking',
  'https://source.unsplash.com/featured/?bartender',
  'https://source.unsplash.com/featured/?coffee',
  'https://source.unsplash.com/featured/?barista',
];

const List<String> kRestaurantNames = [
  'The Hungry Panda',
  'Taste of Italy',
  'Spice Fusion',
  'Sizzling Sushi',
  'Burger Bistro',
  'Cheesy Pizzas',
  'Mexican Delight',
  'Flavors of India',
  'Seafood Sensation',
  'The Grill House',
  'Café Paris',
  'Thai Orchid',
  'Greek Taverna',
  'Rustic BBQ',
  'Sushi Paradise',
  'La Pizzeria',
  'Mama Mia',
  'Soulful Soups',
  'Oceanic Eats',
  'Steakhouse Grill',
  'Veggie Delight',
  'Fire & Ice',
  'Bollywood Spice',
  'The Pasta Place',
  'Chopstick Delight',
  'Savory Tacos',
  'Brasserie Bistro',
  'Falafel King',
  'Fresh Catch',
  'Ramen Express',
  'Gourmet Burgers',
  'Mediterranean Feast',
  'The Curry House',
  'Green Garden',
  'Bakery Bliss',
  'Street Food Stop',
  'Peruvian Flavors',
  'Cajun Corner',
  'Wok n Roll',
  'The Vegan Table',
  'Taste of Brazil',
  'Homestyle Diner',
  'Spanish Tapas',
  'Sizzling BBQ',
  'Sushi Master',
  'Coastal Breeze',
  'Fusion Delights',
  'Farm-to-Table',
  'The Food Factory',
  'Street Taco Truck',
  'Italiano Ristorante',
  'Flavors of Morocco',
];
