// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuRQTv0dRoNYt7aHRgj-9_R9NToxTkbHQ',
    appId: '1:1079204794630:web:fec62d1f0af37897d8ce87',
    messagingSenderId: '1079204794630',
    projectId: 'minihabits-fc330',
    authDomain: 'minihabits-fc330.firebaseapp.com',
    databaseURL: 'https://minihabits-fc330-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minihabits-fc330.appspot.com',
    measurementId: 'G-KYDS6Q57P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3dYsbCX6bCCnzK3t5nsV-56ee8SDFwA',
    appId: '1:1079204794630:android:3d10a913a84eb890d8ce87',
    messagingSenderId: '1079204794630',
    projectId: 'minihabits-fc330',
    databaseURL: 'https://minihabits-fc330-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minihabits-fc330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGglu0JprribC0PBd02UQ__T-KUDL8KU4',
    appId: '1:1079204794630:ios:2cb2e56a6e19eed1d8ce87',
    messagingSenderId: '1079204794630',
    projectId: 'minihabits-fc330',
    databaseURL: 'https://minihabits-fc330-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minihabits-fc330.appspot.com',
    iosClientId: '1079204794630-pjpt1tuv9ovc6ej71itbf17r3tujjmfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniHabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGglu0JprribC0PBd02UQ__T-KUDL8KU4',
    appId: '1:1079204794630:ios:2cb2e56a6e19eed1d8ce87',
    messagingSenderId: '1079204794630',
    projectId: 'minihabits-fc330',
    databaseURL: 'https://minihabits-fc330-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minihabits-fc330.appspot.com',
    iosClientId: '1079204794630-pjpt1tuv9ovc6ej71itbf17r3tujjmfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniHabits',
  );
}
