final List<String> kFoodNames = [
  'Burger',
  'Pizza',
  'Pasta',
  'Salad',
  'Sandwich',
  'Soup',
  'Steak',
  'Sushi',
  'Taco',
  'Wings',
];

final List<String> kFoodImagesUrls = [
  'https://source.unsplash.com/featured/?restaurant',
  'https://source.unsplash.com/featured/?food',
  'https://source.unsplash.com/featured/?dining',
  'https://source.unsplash.com/featured/?cuisine',
  'https://source.unsplash.com/featured/?gastronomy',
  'https://source.unsplash.com/featured/?meal',
  'https://source.unsplash.com/featured/?chef',
  'https://source.unsplash.com/featured/?culinary',
  'https://source.unsplash.com/featured/?gourmet',
  'https://source.unsplash.com/featured/?delicious',
  'https://source.unsplash.com/featured/?tasty',
  'https://source.unsplash.com/featured/?yummy',
  'https://source.unsplash.com/featured/?appetizing',
  'https://source.unsplash.com/featured/?mouthwatering',
  'https://source.unsplash.com/featured/?savor',
  'https://source.unsplash.com/featured/?flavorful',
  'https://source.unsplash.com/featured/?savory',
  'https://source.unsplash.com/featured/?delectable',
  'https://source.unsplash.com/featured/?palatable',
  'https://source.unsplash.com/featured/?scrumptious',
  'https://source.unsplash.com/featured/?tasteful',
  'https://source.unsplash.com/featured/?tempting',
  'https://source.unsplash.com/featured/?delightful',
  'https://source.unsplash.com/featured/?gastronomic',
  'https://source.unsplash.com/featured/?gastro',
  'https://source.unsplash.com/featured/?feast',
  'https://source.unsplash.com/featured/?cook',
  'https://source.unsplash.com/featured/?serve',
  'https://source.unsplash.com/featured/?plate',
  'https://source.unsplash.com/featured/?dish',
  'https://source.unsplash.com/featured/?cuisine',
  'https://source.unsplash.com/featured/?dine',
  'https://source.unsplash.com/featured/?banquet',
  'https://source.unsplash.com/featured/?menu',
  'https://source.unsplash.com/featured/?kitchen',
  'https://source.unsplash.com/featured/?eat',
  'https://source.unsplash.com/featured/?refreshment',
  'https://source.unsplash.com/featured/?nutrition',
  'https://source.unsplash.com/featured/?gourmand',
  'https://source.unsplash.com/featured/?foodie',
  'https://source.unsplash.com/featured/?delicacy',
  'https://source.unsplash.com/featured/?toothsome',
  'https://source.unsplash.com/featured/?catering',
  'https://source.unsplash.com/featured/?dishes',
  'https://source.unsplash.com/featured/?bistro',
  'https://source.unsplash.com/featured/?restaurantinterior',
  'https://source.unsplash.com/featured/?restaurantexterior',
  'https://source.unsplash.com/featured/?chefcooking',
  'https://source.unsplash.com/featured/?bartender',
  'https://source.unsplash.com/featured/?coffee',
  'https://source.unsplash.com/featured/?barista',
];

final List<String> kFoodDescriptions = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, libero sed aliquet ultricies, nisl nunc aliquam dolor, quis aliquet urna nunc eget nunc. Donec auctor, libero sed aliquet ultricies, nisl nunc aliquam dolor, quis aliquet urna nunc eget nunc.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, libero sed aliquet ultricies, nisl nunc aliquam dolor, quis aliquet urna nunc eget nunc. Donec auctor, libero sed aliquet ultricies, nisl nunc aliquam dolor, quis aliquet urna nunc eget nunc.',
];
