final List<String> kOfferNames = [
  'Free dessert',
  '2-for-1 cocktails',
  'Happy Hour: 50% off',
  'Kids eat free',
  '15% off for seniors',
  'Weekend brunch',
  'Lunch combo',
  'Buy one, get one free',
  'Complimentary appetizer',
  'Seasonal menu',
  'Late-night dining',
  'Themed cuisine nights',
  'Chef\'s tasting menu',
  'Outdoor dining',
  'Discounted catering',
  'Bottomless coffee',
  'Takeout and delivery',
  'Monthly prize draw',
  'VIP loyalty program',
  'Private event hosting',
];
